from typing import Protocol

from sum_contracts.models import Metadata


class JobRepository(Protocol):
    def accept(
        self,
        owner: str,
        key: str,
        fingerprint: str,
        source: dict,
        metadata: Metadata,
        document_id: str | None = None,
    ) -> tuple[dict, bool]: ...
    def get(self, job_id: str, owner: str | None = None) -> dict: ...
    def context(self, job_id: str) -> dict: ...
    def progress(self, job_id: str, update: dict) -> dict: ...
    def complete(self, job_id: str, manifest: dict) -> dict: ...
    def fail(self, job_id: str, code: str) -> dict: ...
    def cancel(self, job_id: str, owner: str) -> dict: ...
    def events(self, job_id: str, after: int, owner: str) -> list[dict]: ...
