export const contextRequirements = [
  'ACADEMIC_HISTORY',
  'STUDY_PLAN',
  'ACADEMIC_PROGRAMMING',
  'INSTITUTIONAL_RULES',
] as const
export type AcademicContextRequirement = (typeof contextRequirements)[number]

export const intentRequirements = {
  COMPLETED_CREDITS: ['ACADEMIC_HISTORY'],
  COURSE_STATUS: ['ACADEMIC_HISTORY'],
  GRADE_QUERY: ['ACADEMIC_HISTORY'],
  CHECK_COURSE_ELIGIBILITY: [
    'ACADEMIC_HISTORY',
    'STUDY_PLAN',
    'INSTITUTIONAL_RULES',
  ],
  CHECK_PREREQUISITE_FULFILLMENT: ['ACADEMIC_HISTORY', 'STUDY_PLAN'],
  CHECK_PREREQUISITES: ['STUDY_PLAN'],
  GET_COURSE_SCHEDULE: ['ACADEMIC_PROGRAMMING'],
  LIST_AVAILABLE_COURSES: [
    'ACADEMIC_HISTORY',
    'STUDY_PLAN',
    'ACADEMIC_PROGRAMMING',
    'INSTITUTIONAL_RULES',
  ],
  REMAINING_COURSES: ['ACADEMIC_HISTORY', 'STUDY_PLAN'],
  GENERAL_ACADEMIC_RULE: ['INSTITUTIONAL_RULES'],
  CHECK_SCHEDULE_CONFLICTS: ['ACADEMIC_PROGRAMMING'],
  CHECK_CREDIT_LOAD: ['STUDY_PLAN', 'INSTITUTIONAL_RULES'],
  SIMULATE_ENROLLMENT: [
    'ACADEMIC_HISTORY',
    'STUDY_PLAN',
    'ACADEMIC_PROGRAMMING',
    'INSTITUTIONAL_RULES',
  ],
  OTHER: [],
} as const satisfies Record<string, readonly AcademicContextRequirement[]>
export type AcademicIntent = keyof typeof intentRequirements
