from pathlib import Path
from typing import Protocol

from sum_contracts.models import Chunk, EmbeddingProfile, Page


class Extractor(Protocol):
    def page_count(self, source: Path) -> int: ...
    def extract(self, source: Path, first: int, last: int, options: dict) -> list[Page]: ...


class Tokenizer(Protocol):
    def count(self, text: str) -> int: ...
    def split(self, text: str, limit: int, overlap: int) -> list[str]: ...


class EmbeddingProvider(Protocol):
    @property
    def profile(self) -> EmbeddingProfile: ...
    def embed_passages(self, texts: list[str]) -> list[list[float]]: ...


class VectorRepository(Protocol):
    def begin(self, context: dict, profile: EmbeddingProfile, chunks: int) -> None: ...
    def upsert_batch(
        self,
        generation_id: str,
        chunks: list[Chunk],
        vectors: list[list[float]],
        profile: EmbeddingProfile,
    ) -> None: ...
    def ready(self, generation_id: str, manifest: dict) -> None: ...


class JobReporter(Protocol):
    async def context(self, job_id: str) -> dict: ...
    async def embedding_profile(self, job_id: str, profile: dict) -> None: ...
    async def progress(
        self, job_id: str, operation: str, stage: str, message: str, counts: dict | None = None
    ) -> None: ...
    async def timing(self, job_id: str, data: dict) -> None: ...
    async def complete(self, job_id: str, manifest: dict) -> None: ...
    async def fail(self, job_id: str, code: str) -> None: ...
