allowBuilds:
  '@google/genai': true
  '@prisma/client': false
  better-sqlite3: false
  esbuild: true
  lightningcss: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@tanstack/ai-anthropic@0.19.4'
  - '@tanstack/ai-client@0.36.1'
  - '@tanstack/ai-gemini@0.34.2'
  - '@tanstack/ai-ollama@0.11.12'
  - '@tanstack/ai-openai@0.26.0'
  - '@tanstack/ai-react@0.29.4'
  - '@tanstack/ai@0.64.0'
  - '@tanstack/openai-base@0.12.2'
